=== mistBYiq/Homework/сlasswork/osnovujson/src/com/academy/resources/car-validation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://htp.com/academy"
        xmlns:academy="http://htp.com/academy">

    <element name = "cars">
        <complexType>
            <sequence>
                <element name="car" minOccurs="2"
                         maxOccurs="unbounded"
                         type="academy:Car"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Car">
        <sequence>
            <element name = "ttype" type="string"/>
            <element name = "vin" type="int"/>
            <element name = "color" type="string"/>
            <element name = "year" type="int"/>
            <element name = "model" type="string"/>
        </sequence>
        <attribute name="id" type="int" use="required"/>
    </complexType>
</schema>

=== mistBYiq/Homework/src/main/resources/xmlfile.xml
<?xml version="1.0" encoding="UTF-8"?>
<academy:cars
        xmlns:academy="http://htp.com/academy"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://htp.com/academy car-validation.xsd">
    <car id="1">
        <ttype>sedan</ttype>
        <vin>36548745</vin>
        <color>blue</color>
        <year>2019</year>
        <model>BMW</model>
    </car>
    <!--Comment CTRL+SHIFT+/ -->
    <car id="2">
        <ttype>hatchback</ttype>
        <vin>343762</vin>
        <color>red</color>
        <year>2020</year>
        <model>KIA</model>
    </car>
</academy:cars>
